/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FourInARow;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class AppTest {
    @Test
    @Disabled
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertThat(classUnderTest.getGreeting(), is("Hello World!"));
    }
}
